import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

const translations = {
  ar: {
    siteName: "رحّال",
    home: "الرئيسية",
    destinations: "الوجهات",
    offers: "العروض",
    booking: "الحجز",
    contact: "تواصل معنا",
    bookNow: "احجز الآن",
    language: "اللغة",

    heroSubtitle: "اكتشف العالم معنا",
    heroTitle: "رحلات سياحية لا تُنسى حول العالم",
    heroDescription:
      "اختر وجهتك المفضلة، واستمتع بتجربة سفر متكاملة تشمل الفنادق، الرحلات، والبرامج السياحية.",
    exploreDestinations: "استكشف الوجهات",
    viewOffers: "شاهد العروض",

    destinationsSubtitle: "وجهات مميزة",
    destinationsTitle: "أشهر الرحلات السياحية",
    loadingDestinations: "جاري تحميل الوجهات...",
    destinationsError: "حدث خطأ أثناء تحميل الوجهات من السيرفر",
    noDestinations: "لا توجد وجهات حاليًا",
    startingFrom: "ابتداءً من",
    viewDetails: "عرض التفاصيل",

    offersSubtitle: "عروض خاصة",
    offersTitle: "أفضل العروض لهذا الموسم",
    honeymoonOfferTitle: "عرض شهر العسل",
    honeymoonOfferDescription:
      "7 أيام في المالديف مع فندق 5 نجوم وإفطار يومي وتجربة رومانسية مميزة.",
    familyOfferTitle: "رحلة عائلية إلى دبي",
    familyOfferDescription:
      "برنامج عائلي شامل الفندق، الجولات السياحية، والمواصلات داخل المدينة.",
    istanbulOfferTitle: "إجازة في إسطنبول",
    istanbulOfferDescription:
      "5 أيام بين التاريخ، الأسواق، المطاعم التركية، والرحلات البحرية.",
    discount25: "خصم 25%",
    discount15: "خصم 15%",
    discount20: "خصم 20%",
    bookOffer: "احجز العرض",

    loadingDestinationDetails: "جاري تحميل تفاصيل الوجهة...",
    destinationNotFound: "الوجهة غير موجودة أو حدث خطأ أثناء التحميل",
    backToDestinations: "العودة إلى الوجهات",
    price: "السعر",
    duration: "المدة",
    tripProgram: "برنامج الرحلة",
    noDescription: "لا يوجد وصف حاليًا",
    noProgram: "لا يوجد برنامج مضاف لهذه الرحلة حاليًا",
    untitledDestination: "وجهة بدون اسم",
    notSpecified: "غير محدد",
    notAvailable: "غير محددة",
    bookingSubtitle: "احجز رحلتك",
    bookingTitle: "املأ بيانات الحجز",
    bookingBoxTitle: "خطوتك الأولى نحو رحلة مميزة",
    bookingBoxText:
      "أرسل لنا بياناتك، وسيقوم فريقنا بالتواصل معك لتأكيد التفاصيل واختيار أفضل برنامج سياحي يناسبك.",
    bookingStep1: "اختيار الوجهة المناسبة",
    bookingStep2: "تحديد عدد الأشخاص",
    bookingStep3: "تنسيق الفندق والمواصلات",
    bookingStep4: "تأكيد السعر والبرنامج",
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",
    selectDestination: "اختر الوجهة",
    peopleCount: "عدد الأشخاص",
    additionalNotes: "ملاحظات إضافية",
    confirmBooking: "تأكيد الحجز",
    sending: "جاري الإرسال...",
    bookingRequiredMessage: "يرجى تعبئة جميع بيانات الحجز المطلوبة",
    bookingSuccessMessage: "تم إرسال طلب الحجز بنجاح ✅ سنتواصل معك قريبًا.",
    bookingErrorMessage: "حدث خطأ أثناء إرسال الحجز",
    serverConnectionError: "تعذر الاتصال بالسيرفر. تأكد أن السيرفر يعمل.",
    tripDate: "تاريخ الرحلة",
    tripDatePlaceholder: "مثال: 2026-05-20",
    preferredContactMethod: "طريقة التواصل المفضلة",
    whatsapp: "واتساب",
    call: "اتصال",
    email: "إيميل",
    searchPlaceholder: "ابحث",
    heroSearchTitle: "احجز تجارب وأنشطة لا تُنسى",
    heroSearchPlaceholder: "ابحث حسب الوجهة",
    login: "تسجيل الدخول",
    experiencesSubtitle: "تجارب لا تفوت",
    experiencesTitle: "اكتشف أفضل الرحلات والأنشطة",
    all: "الكل",
    searchResultsFor: "نتائج البحث عن",
    loadingExperiences: "جاري تحميل المحتوى...",
    experiencesError: "حدث خطأ أثناء تحميل المحتوى",
    noExperiences: "لا يوجد محتوى حاليًا",
    emailAddress: "البريد الإلكتروني اختياري",
    adultsCount: "عدد البالغين",
    childrenCount: "عدد الأطفال اختياري",
    bookingSummary: "ملخص الحجز",
    selectedTrip: "الرحلة المختارة",
    totalPeople: "إجمالي الأشخاص",
    estimatedPrice: "السعر التقريبي",
    noPaymentNow: "لن يتم الدفع الآن، سيتواصل معك فريقنا لتأكيد التفاصيل.",
    bookingSuccessTitle: "تم إرسال طلبك بنجاح",
    bookingSuccessText:
      "وصلنا طلبك وسيتواصل معك فريقنا قريبًا لتأكيد التفاصيل.",
    newBooking: "إرسال حجز جديد",
    footerDescription:
      "منصة سياحية تساعدك على اختيار أفضل الرحلات والأنشطة والمعالم حول العالم.",
    quickLinks: "روابط سريعة",
    contactInfo: "معلومات التواصل",
    followUs: "تابعنا",
    rightsReserved: "جميع الحقوق محفوظة",

    contactSubtitle: "تواصل معنا",
    contactTitle: "نحن هنا لمساعدتك",
    contactDescription:
      "لديك سؤال عن رحلة أو حجز؟ أرسل لنا رسالة وسيتواصل معك فريقنا في أقرب وقت.",
    contactPhone: "الهاتف",
    contactEmail: "البريد الإلكتروني",
    contactAddress: "العنوان",
    contactAddressValue: "إسطنبول، تركيا",
    workingHours: "ساعات العمل",
    workingHoursValue: "يوميًا من 9 صباحًا حتى 8 مساءً",
    messageName: "الاسم الكامل",
    messageEmail: "البريد الإلكتروني",
    messagePhone: "رقم الهاتف",
    messageText: "اكتب رسالتك هنا",
    sendMessage: "إرسال الرسالة",
    messageSent: "تم إرسال رسالتك بنجاح ✅",
    noOffers: "لا توجد عروض مميزة حاليًا",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundText: "الرابط الذي تحاول الوصول إليه غير صحيح أو تم نقله.",
    backHome: "العودة للرئيسية",
  },

  en: {
    siteName: "Rahal",
    home: "Home",
    destinations: "Destinations",
    offers: "Offers",
    booking: "Booking",
    contact: "Contact",
    bookNow: "Book Now",
    language: "Language",

    heroSubtitle: "Discover the world with us",
    heroTitle: "Unforgettable travel experiences around the world",
    heroDescription:
      "Choose your favorite destination and enjoy a complete travel experience including hotels, tours, and travel programs.",
    exploreDestinations: "Explore Destinations",
    viewOffers: "View Offers",

    destinationsSubtitle: "Featured Destinations",
    destinationsTitle: "Most Popular Trips",
    loadingDestinations: "Loading destinations...",
    destinationsError: "An error occurred while loading destinations",
    noDestinations: "No destinations available right now",
    startingFrom: "Starting from",
    viewDetails: "View Details",

    offersSubtitle: "Special Offers",
    offersTitle: "Best Offers This Season",
    honeymoonOfferTitle: "Honeymoon Package",
    honeymoonOfferDescription:
      "7 days in the Maldives with a 5-star hotel, daily breakfast, and a romantic experience.",
    familyOfferTitle: "Family Trip to Dubai",
    familyOfferDescription:
      "A family package including hotel, city tours, and transportation.",
    istanbulOfferTitle: "Istanbul Vacation",
    istanbulOfferDescription:
      "5 days between history, markets, Turkish restaurants, and boat tours.",
    discount25: "25% Off",
    discount15: "15% Off",
    discount20: "20% Off",
    bookOffer: "Book Offer",

    loadingDestinationDetails: "Loading destination details...",
    destinationNotFound: "Destination not found or an error occurred",
    backToDestinations: "Back to destinations",
    price: "Price",
    duration: "Duration",
    tripProgram: "Trip Program",
    noDescription: "No description available yet",
    noProgram: "No trip program has been added yet",
    untitledDestination: "Untitled destination",
    notSpecified: "Not specified",
    notAvailable: "Not available",
    bookingSubtitle: "Book Your Trip",
    bookingTitle: "Fill in Booking Details",
    bookingBoxTitle: "Your first step toward a special trip",
    bookingBoxText:
      "Send us your details, and our team will contact you to confirm everything and choose the best travel program for you.",
    bookingStep1: "Choose the right destination",
    bookingStep2: "Set the number of people",
    bookingStep3: "Arrange hotel and transportation",
    bookingStep4: "Confirm price and program",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    selectDestination: "Select destination",
    peopleCount: "Number of people",
    additionalNotes: "Additional notes",
    confirmBooking: "Confirm Booking",
    sending: "Sending...",
    bookingRequiredMessage: "Please fill in all required booking details",
    bookingSuccessMessage:
      "Booking request sent successfully ✅ We will contact you soon.",
    bookingErrorMessage: "An error occurred while sending the booking",
    serverConnectionError:
      "Could not connect to the server. Make sure it is running.",
    tripDate: "Trip Date",
    tripDatePlaceholder: "Example: 2026-05-20",
    preferredContactMethod: "Preferred contact method",
    whatsapp: "WhatsApp",
    call: "Call",
    email: "Email",
    searchPlaceholder: "Search",
    heroSearchTitle: "Book unforgettable experiences and activities",
    heroSearchPlaceholder: "Search by destination",
    login: "Login",
    experiencesSubtitle: "Top experiences",
    experiencesTitle: "Discover the best trips and activities",
    all: "All",
    searchResultsFor: "Search results for",
    loadingExperiences: "Loading content...",
    experiencesError: "An error occurred while loading content",
    noExperiences: "No content available right now",
    emailAddress: "Email address optional",
    adultsCount: "Adults",
    childrenCount: "Children optional",
    bookingSummary: "Booking Summary",
    selectedTrip: "Selected trip",
    totalPeople: "Total people",
    estimatedPrice: "Estimated price",
    noPaymentNow:
      "You will not pay now. Our team will contact you to confirm the details.",
    bookingSuccessTitle: "Your request has been sent",
    bookingSuccessText:
      "We received your request and our team will contact you soon to confirm the details.",
    newBooking: "Send another booking",
    footerDescription:
      "A travel platform that helps you choose the best trips, activities, and attractions around the world.",
    quickLinks: "Quick Links",
    contactInfo: "Contact Info",
    followUs: "Follow Us",
    rightsReserved: "All rights reserved",

    contactSubtitle: "Contact Us",
    contactTitle: "We are here to help",
    contactDescription:
      "Have a question about a trip or booking? Send us a message and our team will contact you soon.",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactAddress: "Address",
    contactAddressValue: "Istanbul, Turkey",
    workingHours: "Working Hours",
    workingHoursValue: "Daily from 9 AM to 8 PM",
    messageName: "Full Name",
    messageEmail: "Email Address",
    messagePhone: "Phone Number",
    messageText: "Write your message here",
    sendMessage: "Send Message",
    messageSent: "Your message has been sent successfully ✅",
    noOffers: "No featured offers available right now",
    notFoundTitle: "Page not found",
    notFoundText:
      "The page you are trying to access does not exist or has been moved.",
    backHome: "Back to Home",
  },

  tr: {
    siteName: "Rahal",
    home: "Ana Sayfa",
    destinations: "Rotalar",
    offers: "Teklifler",
    booking: "Rezervasyon",
    contact: "İletişim",
    bookNow: "Şimdi Rezervasyon Yap",
    language: "Dil",

    heroSubtitle: "Dünyayı bizimle keşfedin",
    heroTitle: "Dünya çapında unutulmaz seyahat deneyimleri",
    heroDescription:
      "Favori destinasyonunuzu seçin; oteller, turlar ve seyahat programlarıyla eksiksiz bir tatil deneyimi yaşayın.",
    exploreDestinations: "Rotaları Keşfet",
    viewOffers: "Teklifleri Gör",

    destinationsSubtitle: "Öne Çıkan Rotalar",
    destinationsTitle: "En Popüler Turlar",
    loadingDestinations: "Rotalar yükleniyor...",
    destinationsError: "Rotalar yüklenirken bir hata oluştu",
    noDestinations: "Şu anda rota bulunmuyor",
    startingFrom: "Başlangıç fiyatı",
    viewDetails: "Detayları Gör",

    offersSubtitle: "Özel Teklifler",
    offersTitle: "Bu Sezonun En İyi Teklifleri",
    honeymoonOfferTitle: "Balayı Paketi",
    honeymoonOfferDescription:
      "Maldivler’de 5 yıldızlı otel, günlük kahvaltı ve romantik deneyimle 7 gün.",
    familyOfferTitle: "Dubai Aile Turu",
    familyOfferDescription:
      "Otel, şehir turları ve ulaşımı içeren aile paketi.",
    istanbulOfferTitle: "İstanbul Tatili",
    istanbulOfferDescription:
      "Tarih, pazarlar, Türk restoranları ve tekne turlarıyla 5 gün.",
    discount25: "%25 İndirim",
    discount15: "%15 İndirim",
    discount20: "%20 İndirim",
    bookOffer: "Teklifi Rezerve Et",

    loadingDestinationDetails: "Rota detayları yükleniyor...",
    destinationNotFound: "Rota bulunamadı veya bir hata oluştu",
    backToDestinations: "Rotalara geri dön",
    price: "Fiyat",
    duration: "Süre",
    tripProgram: "Tur Programı",
    noDescription: "Henüz açıklama yok",
    noProgram: "Bu tur için henüz program eklenmedi",
    untitledDestination: "İsimsiz rota",
    notSpecified: "Belirtilmemiş",
    notAvailable: "Mevcut değil",
    bookingSubtitle: "Seyahatinizi Rezerve Edin",
    bookingTitle: "Rezervasyon Bilgilerini Doldurun",
    bookingBoxTitle: "Özel bir yolculuğa ilk adımınız",
    bookingBoxText:
      "Bilgilerinizi gönderin, ekibimiz detayları onaylamak ve size en uygun seyahat programını seçmek için sizinle iletişime geçecektir.",
    bookingStep1: "Uygun rotayı seçme",
    bookingStep2: "Kişi sayısını belirleme",
    bookingStep3: "Otel ve ulaşımı ayarlama",
    bookingStep4: "Fiyat ve programı onaylama",
    fullName: "Ad Soyad",
    phoneNumber: "Telefon Numarası",
    selectDestination: "Rota seçin",
    peopleCount: "Kişi sayısı",
    additionalNotes: "Ek notlar",
    confirmBooking: "Rezervasyonu Onayla",
    sending: "Gönderiliyor...",
    bookingRequiredMessage: "Lütfen gerekli rezervasyon bilgilerini doldurun",
    bookingSuccessMessage:
      "Rezervasyon talebi başarıyla gönderildi ✅ Yakında sizinle iletişime geçeceğiz.",
    bookingErrorMessage: "Rezervasyon gönderilirken bir hata oluştu",
    serverConnectionError:
      "Sunucuya bağlanılamadı. Sunucunun çalıştığından emin olun.",
    tripDate: "Seyahat Tarihi",
    tripDatePlaceholder: "Örnek: 2026-05-20",
    preferredContactMethod: "Tercih edilen iletişim yöntemi",
    whatsapp: "WhatsApp",
    call: "Arama",
    email: "E-posta",
    searchPlaceholder: "Ara",
    heroSearchTitle: "Unutulmaz turlar ve aktiviteler rezerve edin",
    heroSearchPlaceholder: "Rotaya göre ara",
    login: "Giriş",
    experiencesSubtitle: "Kaçırılmayacak deneyimler",
    experiencesTitle: "En iyi turları ve aktiviteleri keşfedin",
    all: "Tümü",
    searchResultsFor: "Arama sonuçları",
    loadingExperiences: "İçerik yükleniyor...",
    experiencesError: "İçerik yüklenirken bir hata oluştu",
    noExperiences: "Şu anda içerik bulunmuyor",
    emailAddress: "E-posta adresi isteğe bağlı",
    adultsCount: "Yetişkin sayısı",
    childrenCount: "Çocuk sayısı isteğe bağlı",
    bookingSummary: "Rezervasyon Özeti",
    selectedTrip: "Seçilen tur",
    totalPeople: "Toplam kişi",
    estimatedPrice: "Tahmini fiyat",
    noPaymentNow:
      "Şimdi ödeme yapmayacaksınız. Ekibimiz detayları onaylamak için sizinle iletişime geçecektir.",
    bookingSuccessTitle: "Talebiniz gönderildi",
    bookingSuccessText:
      "Talebinizi aldık. Ekibimiz detayları onaylamak için yakında sizinle iletişime geçecektir.",
    newBooking: "Yeni rezervasyon gönder",
    footerDescription:
      "Dünyadaki en iyi turları, aktiviteleri ve gezilecek yerleri seçmenize yardımcı olan bir seyahat platformu.",
    quickLinks: "Hızlı Bağlantılar",
    contactInfo: "İletişim Bilgileri",
    followUs: "Bizi Takip Edin",
    rightsReserved: "Tüm hakları saklıdır",

    contactSubtitle: "İletişim",
    contactTitle: "Size yardımcı olmak için buradayız",
    contactDescription:
      "Bir tur veya rezervasyon hakkında sorunuz mu var? Bize mesaj gönderin, ekibimiz yakında sizinle iletişime geçecektir.",
    contactPhone: "Telefon",
    contactEmail: "E-posta",
    contactAddress: "Adres",
    contactAddressValue: "İstanbul, Türkiye",
    workingHours: "Çalışma Saatleri",
    workingHoursValue: "Her gün 09:00 - 20:00",
    messageName: "Ad Soyad",
    messageEmail: "E-posta Adresi",
    messagePhone: "Telefon Numarası",
    messageText: "Mesajınızı buraya yazın",
    sendMessage: "Mesaj Gönder",
    messageSent: "Mesajınız başarıyla gönderildi ✅",
    noOffers: "Şu anda öne çıkan teklif yok",
    notFoundTitle: "Sayfa bulunamadı",
    notFoundText: "Ulaşmaya çalıştığınız sayfa mevcut değil veya taşınmış.",
    backHome: "Ana sayfaya dön",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "ar";
  });

  useEffect(() => {
    localStorage.setItem("language", language);

    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
